server:
  http:
    network: tcp
    addr: 0.0.0.0:8003
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 1s
  register:
   address : 101.43.63.229
   port : 8848
   namespaceId: public
   accessKey: nacos
   secretKey: nacos
   timeoutMs: 5000
   logLevel: debug
data:
  kafka:
    topic: "logic-single"
    brokers: ["101.43.63.229:9092"]
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
