// Copyright 2022 gqzcl <gqzcl@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: logic/v1/msg_type.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 图像类型枚举
type ImageFormat int32

const (
	ImageFormat_JPG   ImageFormat = 0
	ImageFormat_GIF   ImageFormat = 1
	ImageFormat_PNG   ImageFormat = 3
	ImageFormat_BMP   ImageFormat = 4
	ImageFormat_Other ImageFormat = 5
)

// Enum value maps for ImageFormat.
var (
	ImageFormat_name = map[int32]string{
		0: "JPG",
		1: "GIF",
		3: "PNG",
		4: "BMP",
		5: "Other",
	}
	ImageFormat_value = map[string]int32{
		"JPG":   0,
		"GIF":   1,
		"PNG":   3,
		"BMP":   4,
		"Other": 5,
	}
)

func (x ImageFormat) Enum() *ImageFormat {
	p := new(ImageFormat)
	*p = x
	return p
}

func (x ImageFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_logic_v1_msg_type_proto_enumTypes[0].Descriptor()
}

func (ImageFormat) Type() protoreflect.EnumType {
	return &file_logic_v1_msg_type_proto_enumTypes[0]
}

func (x ImageFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageFormat.Descriptor instead.
func (ImageFormat) EnumDescriptor() ([]byte, []int) {
	return file_logic_v1_msg_type_proto_rawDescGZIP(), []int{0}
}

type ImageInfo_ImageType int32

const (
	ImageInfo_big       ImageInfo_ImageType = 0 // 大图
	ImageInfo_origin    ImageInfo_ImageType = 1 // 原图
	ImageInfo_thumbnail ImageInfo_ImageType = 2 // 缩略图
)

// Enum value maps for ImageInfo_ImageType.
var (
	ImageInfo_ImageType_name = map[int32]string{
		0: "big",
		1: "origin",
		2: "thumbnail",
	}
	ImageInfo_ImageType_value = map[string]int32{
		"big":       0,
		"origin":    1,
		"thumbnail": 2,
	}
)

func (x ImageInfo_ImageType) Enum() *ImageInfo_ImageType {
	p := new(ImageInfo_ImageType)
	*p = x
	return p
}

func (x ImageInfo_ImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageInfo_ImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_logic_v1_msg_type_proto_enumTypes[1].Descriptor()
}

func (ImageInfo_ImageType) Type() protoreflect.EnumType {
	return &file_logic_v1_msg_type_proto_enumTypes[1]
}

func (x ImageInfo_ImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageInfo_ImageType.Descriptor instead.
func (ImageInfo_ImageType) EnumDescriptor() ([]byte, []int) {
	return file_logic_v1_msg_type_proto_rawDescGZIP(), []int{1, 0}
}

type MsgVideo_VideoFormat int32

const (
	MsgVideo_mp4 MsgVideo_VideoFormat = 0
	MsgVideo_avi MsgVideo_VideoFormat = 1
)

// Enum value maps for MsgVideo_VideoFormat.
var (
	MsgVideo_VideoFormat_name = map[int32]string{
		0: "mp4",
		1: "avi",
	}
	MsgVideo_VideoFormat_value = map[string]int32{
		"mp4": 0,
		"avi": 1,
	}
)

func (x MsgVideo_VideoFormat) Enum() *MsgVideo_VideoFormat {
	p := new(MsgVideo_VideoFormat)
	*p = x
	return p
}

func (x MsgVideo_VideoFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgVideo_VideoFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_logic_v1_msg_type_proto_enumTypes[2].Descriptor()
}

func (MsgVideo_VideoFormat) Type() protoreflect.EnumType {
	return &file_logic_v1_msg_type_proto_enumTypes[2]
}

func (x MsgVideo_VideoFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgVideo_VideoFormat.Descriptor instead.
func (MsgVideo_VideoFormat) EnumDescriptor() ([]byte, []int) {
	return file_logic_v1_msg_type_proto_rawDescGZIP(), []int{5, 0}
}

// 文本消息
type MsgText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *MsgText) Reset() {
	*x = MsgText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_v1_msg_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgText) ProtoMessage() {}

func (x *MsgText) ProtoReflect() protoreflect.Message {
	mi := &file_logic_v1_msg_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgText.ProtoReflect.Descriptor instead.
func (*MsgText) Descriptor() ([]byte, []int) {
	return file_logic_v1_msg_type_proto_rawDescGZIP(), []int{0}
}

func (x *MsgText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// 图片信息
type ImageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   ImageInfo_ImageType `protobuf:"varint,1,opt,name=type,proto3,enum=api.logic.v1.ImageInfo_ImageType" json:"type,omitempty"`
	Size   int64               `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Width  int64               `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height int64               `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	URL    string              `protobuf:"bytes,5,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_v1_msg_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_logic_v1_msg_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_logic_v1_msg_type_proto_rawDescGZIP(), []int{1}
}

func (x *ImageInfo) GetType() ImageInfo_ImageType {
	if x != nil {
		return x.Type
	}
	return ImageInfo_big
}

func (x *ImageInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ImageInfo) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageInfo) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageInfo) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

// 图像消息
type MsgImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID           string       `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	ImageFormat    ImageFormat  `protobuf:"varint,2,opt,name=image_format,json=imageFormat,proto3,enum=api.logic.v1.ImageFormat" json:"image_format,omitempty"`
	ImageInfoArray []*ImageInfo `protobuf:"bytes,3,rep,name=image_info_array,json=imageInfoArray,proto3" json:"image_info_array,omitempty"`
}

func (x *MsgImage) Reset() {
	*x = MsgImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_v1_msg_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgImage) ProtoMessage() {}

func (x *MsgImage) ProtoReflect() protoreflect.Message {
	mi := &file_logic_v1_msg_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgImage.ProtoReflect.Descriptor instead.
func (*MsgImage) Descriptor() ([]byte, []int) {
	return file_logic_v1_msg_type_proto_rawDescGZIP(), []int{2}
}

func (x *MsgImage) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *MsgImage) GetImageFormat() ImageFormat {
	if x != nil {
		return x.ImageFormat
	}
	return ImageFormat_JPG
}

func (x *MsgImage) GetImageInfoArray() []*ImageInfo {
	if x != nil {
		return x.ImageInfoArray
	}
	return nil
}

// 表情消息
type MsgFace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *MsgFace) Reset() {
	*x = MsgFace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_v1_msg_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFace) ProtoMessage() {}

func (x *MsgFace) ProtoReflect() protoreflect.Message {
	mi := &file_logic_v1_msg_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFace.ProtoReflect.Descriptor instead.
func (*MsgFace) Descriptor() ([]byte, []int) {
	return file_logic_v1_msg_type_proto_rawDescGZIP(), []int{3}
}

func (x *MsgFace) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// 文件消息
type MsgFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID     string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	URL      string `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	FileSize uint32 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileName string `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
}

func (x *MsgFile) Reset() {
	*x = MsgFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_v1_msg_type_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFile) ProtoMessage() {}

func (x *MsgFile) ProtoReflect() protoreflect.Message {
	mi := &file_logic_v1_msg_type_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFile.ProtoReflect.Descriptor instead.
func (*MsgFile) Descriptor() ([]byte, []int) {
	return file_logic_v1_msg_type_proto_rawDescGZIP(), []int{4}
}

func (x *MsgFile) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *MsgFile) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *MsgFile) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *MsgFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// 视频消息
type MsgVideo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoUUID   string               `protobuf:"bytes,1,opt,name=VideoUUID,proto3" json:"VideoUUID,omitempty"`                                                                // 视频ID
	VideoURL    string               `protobuf:"bytes,2,opt,name=VideoURL,proto3" json:"VideoURL,omitempty"`                                                                  // 视频地址
	VideoSize   uint32               `protobuf:"varint,3,opt,name=VideoSize,proto3" json:"VideoSize,omitempty"`                                                               // 视频大小
	VideoSecond uint32               `protobuf:"varint,4,opt,name=VideoSecond,proto3" json:"VideoSecond,omitempty"`                                                           // 视频时长
	VideoFormat MsgVideo_VideoFormat `protobuf:"varint,5,opt,name=Video_format,json=VideoFormat,proto3,enum=api.logic.v1.MsgVideo_VideoFormat" json:"Video_format,omitempty"` // 视频格式
	ThumbURL    string               `protobuf:"bytes,7,opt,name=ThumbURL,proto3" json:"ThumbURL,omitempty"`                                                                  // 缩略图地址
	ThumbUUID   string               `protobuf:"bytes,8,opt,name=ThumbUUID,proto3" json:"ThumbUUID,omitempty"`                                                                // 缩略图ID
	ThumbSize   uint32               `protobuf:"varint,9,opt,name=ThumbSize,proto3" json:"ThumbSize,omitempty"`                                                               // 缩略图大小
	ThumbWidth  uint32               `protobuf:"varint,10,opt,name=ThumbWidth,proto3" json:"ThumbWidth,omitempty"`
	ThumbHeight uint32               `protobuf:"varint,11,opt,name=ThumbHeight,proto3" json:"ThumbHeight,omitempty"`
	ThumbFormat ImageFormat          `protobuf:"varint,12,opt,name=ThumbFormat,proto3,enum=api.logic.v1.ImageFormat" json:"ThumbFormat,omitempty"` // 缩略图格式
}

func (x *MsgVideo) Reset() {
	*x = MsgVideo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_v1_msg_type_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgVideo) ProtoMessage() {}

func (x *MsgVideo) ProtoReflect() protoreflect.Message {
	mi := &file_logic_v1_msg_type_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgVideo.ProtoReflect.Descriptor instead.
func (*MsgVideo) Descriptor() ([]byte, []int) {
	return file_logic_v1_msg_type_proto_rawDescGZIP(), []int{5}
}

func (x *MsgVideo) GetVideoUUID() string {
	if x != nil {
		return x.VideoUUID
	}
	return ""
}

func (x *MsgVideo) GetVideoURL() string {
	if x != nil {
		return x.VideoURL
	}
	return ""
}

func (x *MsgVideo) GetVideoSize() uint32 {
	if x != nil {
		return x.VideoSize
	}
	return 0
}

func (x *MsgVideo) GetVideoSecond() uint32 {
	if x != nil {
		return x.VideoSecond
	}
	return 0
}

func (x *MsgVideo) GetVideoFormat() MsgVideo_VideoFormat {
	if x != nil {
		return x.VideoFormat
	}
	return MsgVideo_mp4
}

func (x *MsgVideo) GetThumbURL() string {
	if x != nil {
		return x.ThumbURL
	}
	return ""
}

func (x *MsgVideo) GetThumbUUID() string {
	if x != nil {
		return x.ThumbUUID
	}
	return ""
}

func (x *MsgVideo) GetThumbSize() uint32 {
	if x != nil {
		return x.ThumbSize
	}
	return 0
}

func (x *MsgVideo) GetThumbWidth() uint32 {
	if x != nil {
		return x.ThumbWidth
	}
	return 0
}

func (x *MsgVideo) GetThumbHeight() uint32 {
	if x != nil {
		return x.ThumbHeight
	}
	return 0
}

func (x *MsgVideo) GetThumbFormat() ImageFormat {
	if x != nil {
		return x.ThumbFormat
	}
	return ImageFormat_JPG
}

// 音频消息
type MsgSound struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size   uint32 `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Second uint32 `protobuf:"varint,2,opt,name=Second,proto3" json:"Second,omitempty"`
	UUID   string `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	URL    string `protobuf:"bytes,4,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *MsgSound) Reset() {
	*x = MsgSound{}
	if protoimpl.UnsafeEnabled {
		mi := &file_logic_v1_msg_type_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSound) ProtoMessage() {}

func (x *MsgSound) ProtoReflect() protoreflect.Message {
	mi := &file_logic_v1_msg_type_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSound.ProtoReflect.Descriptor instead.
func (*MsgSound) Descriptor() ([]byte, []int) {
	return file_logic_v1_msg_type_proto_rawDescGZIP(), []int{6}
}

func (x *MsgSound) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MsgSound) GetSecond() uint32 {
	if x != nil {
		return x.Second
	}
	return 0
}

func (x *MsgSound) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *MsgSound) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

var File_logic_v1_msg_type_proto protoreflect.FileDescriptor

var file_logic_v1_msg_type_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x65,
	0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xc7, 0x01, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x52, 0x4c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x22,
	0x2f, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03,
	0x62, 0x69, 0x67, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x10, 0x02,
	0x22, 0x9f, 0x01, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49,
	0x44, 0x12, 0x3c, 0x0a, 0x0c, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6c, 0x6f,
	0x67, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x52, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12,
	0x41, 0x0a, 0x10, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x61, 0x72,
	0x72, 0x61, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0e, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x72, 0x72,
	0x61, 0x79, 0x22, 0x1f, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x46, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x22, 0x69, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55,
	0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x55, 0x52, 0x4c, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xc3,
	0x03, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x55, 0x52, 0x4c, 0x12, 0x1c, 0x0a, 0x09, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x12, 0x45, 0x0a, 0x0c, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52,
	0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x52, 0x4c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x54, 0x68, 0x75, 0x6d, 0x62, 0x55, 0x52, 0x4c, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x68, 0x75, 0x6d,
	0x62, 0x55, 0x55, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x68, 0x75,
	0x6d, 0x62, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x54, 0x68, 0x75, 0x6d, 0x62,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x57, 0x69, 0x64,
	0x74, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x57,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x54, 0x68, 0x75, 0x6d, 0x62,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x46,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x0b, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x22, 0x1f, 0x0a, 0x0b, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x12, 0x07, 0x0a, 0x03, 0x6d, 0x70, 0x34, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x61,
	0x76, 0x69, 0x10, 0x01, 0x22, 0x5c, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x53, 0x6f, 0x75, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x55, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55,
	0x52, 0x4c, 0x2a, 0x3c, 0x0a, 0x0b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x12, 0x07, 0x0a, 0x03, 0x4a, 0x50, 0x47, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x49,
	0x46, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03,
	0x42, 0x4d, 0x50, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x10, 0x05,
	0x42, 0x32, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x17,
	0x61, 0x72, 0x6f, 0x64, 0x2d, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0xa2, 0x02, 0x0a, 0x41, 0x50, 0x49, 0x4c, 0x6f, 0x67,
	0x69, 0x63, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_logic_v1_msg_type_proto_rawDescOnce sync.Once
	file_logic_v1_msg_type_proto_rawDescData = file_logic_v1_msg_type_proto_rawDesc
)

func file_logic_v1_msg_type_proto_rawDescGZIP() []byte {
	file_logic_v1_msg_type_proto_rawDescOnce.Do(func() {
		file_logic_v1_msg_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_logic_v1_msg_type_proto_rawDescData)
	})
	return file_logic_v1_msg_type_proto_rawDescData
}

var file_logic_v1_msg_type_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_logic_v1_msg_type_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_logic_v1_msg_type_proto_goTypes = []interface{}{
	(ImageFormat)(0),          // 0: api.logic.v1.ImageFormat
	(ImageInfo_ImageType)(0),  // 1: api.logic.v1.ImageInfo.ImageType
	(MsgVideo_VideoFormat)(0), // 2: api.logic.v1.MsgVideo.VideoFormat
	(*MsgText)(nil),           // 3: api.logic.v1.MsgText
	(*ImageInfo)(nil),         // 4: api.logic.v1.ImageInfo
	(*MsgImage)(nil),          // 5: api.logic.v1.MsgImage
	(*MsgFace)(nil),           // 6: api.logic.v1.MsgFace
	(*MsgFile)(nil),           // 7: api.logic.v1.MsgFile
	(*MsgVideo)(nil),          // 8: api.logic.v1.MsgVideo
	(*MsgSound)(nil),          // 9: api.logic.v1.MsgSound
}
var file_logic_v1_msg_type_proto_depIdxs = []int32{
	1, // 0: api.logic.v1.ImageInfo.type:type_name -> api.logic.v1.ImageInfo.ImageType
	0, // 1: api.logic.v1.MsgImage.image_format:type_name -> api.logic.v1.ImageFormat
	4, // 2: api.logic.v1.MsgImage.image_info_array:type_name -> api.logic.v1.ImageInfo
	2, // 3: api.logic.v1.MsgVideo.Video_format:type_name -> api.logic.v1.MsgVideo.VideoFormat
	0, // 4: api.logic.v1.MsgVideo.ThumbFormat:type_name -> api.logic.v1.ImageFormat
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_logic_v1_msg_type_proto_init() }
func file_logic_v1_msg_type_proto_init() {
	if File_logic_v1_msg_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_logic_v1_msg_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_v1_msg_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_v1_msg_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_v1_msg_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_v1_msg_type_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_v1_msg_type_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgVideo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_logic_v1_msg_type_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSound); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_logic_v1_msg_type_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logic_v1_msg_type_proto_goTypes,
		DependencyIndexes: file_logic_v1_msg_type_proto_depIdxs,
		EnumInfos:         file_logic_v1_msg_type_proto_enumTypes,
		MessageInfos:      file_logic_v1_msg_type_proto_msgTypes,
	}.Build()
	File_logic_v1_msg_type_proto = out.File
	file_logic_v1_msg_type_proto_rawDesc = nil
	file_logic_v1_msg_type_proto_goTypes = nil
	file_logic_v1_msg_type_proto_depIdxs = nil
}
