// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"arod-im/app/arod-im-connector/internal/biz"
	"arod-im/app/arod-im-connector/internal/conf"
	"arod-im/app/arod-im-connector/internal/data"
	"arod-im/app/arod-im-connector/internal/server"
	"arod-im/app/arod-im-connector/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	bucketRepo := data.NewBucketRepo(dataData, logger)
	bucketUsecase := biz.NewBucketUsecase(bucketRepo, logger)
	connectorService := service.NewConnectorService(confServer, bucketUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, connectorService, logger)
	websocketServer := server.NewWebsocketServer(confServer, connectorService)
	registry := server.NewNacosRegister(confServer, connectorService)
	app := newApp(logger, grpcServer, websocketServer, registry)
	return app, func() {
		cleanup()
	}, nil
}
