// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"arod-im/app/comet/internal/conf"
	"arod-im/app/comet/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func initApp(consul *conf.Consul, logger log.Logger) (*kratos.App, func(), error) {
	registrar := server.NewRegistrar(consul)
	app := newApp(logger, registrar)
	return app, func() {
	}, nil
}
