// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: connector/v1/connector.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConnectorClient is the client API for Connector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConnectorClient interface {
	// PushMsg push by key or mid
	SingleSend(ctx context.Context, in *SingleSendReq, opts ...grpc.CallOption) (*SingleSendReply, error)
	// Broadcast send to every enrity
	GroupSend(ctx context.Context, in *GroupSendReq, opts ...grpc.CallOption) (*GroupSendReply, error)
	// BroadcastRoom broadcast to one room
	RoomSend(ctx context.Context, in *RoomSendReq, opts ...grpc.CallOption) (*RoomSendReply, error)
	// Rooms get all rooms
	Broadcast(ctx context.Context, in *BroadcastReq, opts ...grpc.CallOption) (*BroadcastReply, error)
}

type connectorClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectorClient(cc grpc.ClientConnInterface) ConnectorClient {
	return &connectorClient{cc}
}

func (c *connectorClient) SingleSend(ctx context.Context, in *SingleSendReq, opts ...grpc.CallOption) (*SingleSendReply, error) {
	out := new(SingleSendReply)
	err := c.cc.Invoke(ctx, "/api.connector.v1.Connector/SingleSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorClient) GroupSend(ctx context.Context, in *GroupSendReq, opts ...grpc.CallOption) (*GroupSendReply, error) {
	out := new(GroupSendReply)
	err := c.cc.Invoke(ctx, "/api.connector.v1.Connector/GroupSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorClient) RoomSend(ctx context.Context, in *RoomSendReq, opts ...grpc.CallOption) (*RoomSendReply, error) {
	out := new(RoomSendReply)
	err := c.cc.Invoke(ctx, "/api.connector.v1.Connector/RoomSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorClient) Broadcast(ctx context.Context, in *BroadcastReq, opts ...grpc.CallOption) (*BroadcastReply, error) {
	out := new(BroadcastReply)
	err := c.cc.Invoke(ctx, "/api.connector.v1.Connector/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectorServer is the server API for Connector service.
// All implementations must embed UnimplementedConnectorServer
// for forward compatibility
type ConnectorServer interface {
	// PushMsg push by key or mid
	SingleSend(context.Context, *SingleSendReq) (*SingleSendReply, error)
	// Broadcast send to every enrity
	GroupSend(context.Context, *GroupSendReq) (*GroupSendReply, error)
	// BroadcastRoom broadcast to one room
	RoomSend(context.Context, *RoomSendReq) (*RoomSendReply, error)
	// Rooms get all rooms
	Broadcast(context.Context, *BroadcastReq) (*BroadcastReply, error)
	mustEmbedUnimplementedConnectorServer()
}

// UnimplementedConnectorServer must be embedded to have forward compatible implementations.
type UnimplementedConnectorServer struct {
}

func (UnimplementedConnectorServer) SingleSend(context.Context, *SingleSendReq) (*SingleSendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SingleSend not implemented")
}
func (UnimplementedConnectorServer) GroupSend(context.Context, *GroupSendReq) (*GroupSendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GroupSend not implemented")
}
func (UnimplementedConnectorServer) RoomSend(context.Context, *RoomSendReq) (*RoomSendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoomSend not implemented")
}
func (UnimplementedConnectorServer) Broadcast(context.Context, *BroadcastReq) (*BroadcastReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedConnectorServer) mustEmbedUnimplementedConnectorServer() {}

// UnsafeConnectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectorServer will
// result in compilation errors.
type UnsafeConnectorServer interface {
	mustEmbedUnimplementedConnectorServer()
}

func RegisterConnectorServer(s grpc.ServiceRegistrar, srv ConnectorServer) {
	s.RegisterService(&Connector_ServiceDesc, srv)
}

func _Connector_SingleSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleSendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).SingleSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.connector.v1.Connector/SingleSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).SingleSend(ctx, req.(*SingleSendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connector_GroupSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupSendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).GroupSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.connector.v1.Connector/GroupSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).GroupSend(ctx, req.(*GroupSendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connector_RoomSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomSendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).RoomSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.connector.v1.Connector/RoomSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).RoomSend(ctx, req.(*RoomSendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Connector_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.connector.v1.Connector/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServer).Broadcast(ctx, req.(*BroadcastReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Connector_ServiceDesc is the grpc.ServiceDesc for Connector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Connector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.connector.v1.Connector",
	HandlerType: (*ConnectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SingleSend",
			Handler:    _Connector_SingleSend_Handler,
		},
		{
			MethodName: "GroupSend",
			Handler:    _Connector_GroupSend_Handler,
		},
		{
			MethodName: "RoomSend",
			Handler:    _Connector_RoomSend_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _Connector_Broadcast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connector/v1/connector.proto",
}
