// Copyright 2022 gqzcl <gqzcl@qq.com>. All rights reserved.
// Use of this source code is governed by a MIT style

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: job/v1/job.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType string `protobuf:"bytes,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	// 根据不同消息类型有不同的消息内容
	MsgContent *structpb.Struct `protobuf:"bytes,2,opt,name=msg_content,json=msgContent,proto3" json:"msg_content,omitempty"`
}

func (x *MsgBody) Reset() {
	*x = MsgBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_v1_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBody) ProtoMessage() {}

func (x *MsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBody.ProtoReflect.Descriptor instead.
func (*MsgBody) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *MsgBody) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *MsgBody) GetMsgContent() *structpb.Struct {
	if x != nil {
		return x.MsgContent
	}
	return nil
}

type SingleSendMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  map[string]string `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SenderId string            `protobuf:"bytes,2,opt,name=senderId,proto3" json:"senderId,omitempty"`
	Seq      string            `protobuf:"bytes,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Msg      []*MsgBody        `protobuf:"bytes,4,rep,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SingleSendMsg) Reset() {
	*x = SingleSendMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_v1_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleSendMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleSendMsg) ProtoMessage() {}

func (x *SingleSendMsg) ProtoReflect() protoreflect.Message {
	mi := &file_job_v1_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleSendMsg.ProtoReflect.Descriptor instead.
func (*SingleSendMsg) Descriptor() ([]byte, []int) {
	return file_job_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *SingleSendMsg) GetAddress() map[string]string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *SingleSendMsg) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SingleSendMsg) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

func (x *SingleSendMsg) GetMsg() []*MsgBody {
	if x != nil {
		return x.Msg
	}
	return nil
}

var File_job_v1_job_proto protoreflect.FileDescriptor

var file_job_v1_job_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6a, 0x6f, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x52, 0x0a, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xe2, 0x01, 0x0a,
	0x0d, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x40,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x25,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x3a, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x32, 0x05, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x42, 0x25, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e,
	0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x15, 0x61, 0x72, 0x6f, 0x64, 0x2d, 0x69,
	0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6a, 0x6f, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_job_v1_job_proto_rawDescOnce sync.Once
	file_job_v1_job_proto_rawDescData = file_job_v1_job_proto_rawDesc
)

func file_job_v1_job_proto_rawDescGZIP() []byte {
	file_job_v1_job_proto_rawDescOnce.Do(func() {
		file_job_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_job_v1_job_proto_rawDescData)
	})
	return file_job_v1_job_proto_rawDescData
}

var file_job_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_job_v1_job_proto_goTypes = []interface{}{
	(*MsgBody)(nil),         // 0: api.job.v1.MsgBody
	(*SingleSendMsg)(nil),   // 1: api.job.v1.SingleSendMsg
	nil,                     // 2: api.job.v1.SingleSendMsg.AddressEntry
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
}
var file_job_v1_job_proto_depIdxs = []int32{
	3, // 0: api.job.v1.MsgBody.msg_content:type_name -> google.protobuf.Struct
	2, // 1: api.job.v1.SingleSendMsg.address:type_name -> api.job.v1.SingleSendMsg.AddressEntry
	0, // 2: api.job.v1.SingleSendMsg.msg:type_name -> api.job.v1.MsgBody
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_job_v1_job_proto_init() }
func file_job_v1_job_proto_init() {
	if File_job_v1_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_job_v1_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_v1_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleSendMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_job_v1_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_v1_job_proto_goTypes,
		DependencyIndexes: file_job_v1_job_proto_depIdxs,
		MessageInfos:      file_job_v1_job_proto_msgTypes,
	}.Build()
	File_job_v1_job_proto = out.File
	file_job_v1_job_proto_rawDesc = nil
	file_job_v1_job_proto_goTypes = nil
	file_job_v1_job_proto_depIdxs = nil
}
