// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: job/v1/job.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_job_v1_job_proto protoreflect.FileDescriptor

var file_job_v1_job_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6a, 0x6f, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x76, 0x31, 0x32, 0x05,
	0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x42, 0x25, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x6a, 0x6f, 0x62,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x15, 0x61, 0x72, 0x6f, 0x64, 0x2d, 0x69, 0x6d, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x6a, 0x6f, 0x62, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var file_job_v1_job_proto_goTypes = []interface{}{}
var file_job_v1_job_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_job_v1_job_proto_init() }
func file_job_v1_job_proto_init() {
	if File_job_v1_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_job_v1_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_v1_job_proto_goTypes,
		DependencyIndexes: file_job_v1_job_proto_depIdxs,
	}.Build()
	File_job_v1_job_proto = out.File
	file_job_v1_job_proto_rawDesc = nil
	file_job_v1_job_proto_goTypes = nil
	file_job_v1_job_proto_depIdxs = nil
}
